---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether CircleCI CLI is installed
      ansible.builtin.command: circleci version
      register: circlecicli_installed
      changed_when: false

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Make sure CircleCI CLI is installed
      ansible.builtin.debug:
        var: circlecicli_installed

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
