---
- name: Verify
  hosts: all

  tasks:
    - name: Install which
      become: true
      ansible.builtin.package:
        name: which

    - name: Check whether CircleCI CLI is installed
      ansible.builtin.command: which circleci
      environment:
        TERM: xterm
      register: CIRCLECICLI_INSTALLED
      changed_when: false

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: OS_VERSION
      changed_when: false

    - name: Make sure CircleCI CLI is installed
      ansible.builtin.debug:
        var: CIRCLECICLI_INSTALLED

    - name: Show OS version
      ansible.builtin.debug:
        var: OS_VERSION
