---
- name: Verify
  hosts: all

  tasks:
    - name: Install which
      package:
        name: which

    - name: Check whether exa installed
      command: which circleci
      environment:
        TERM: xterm
      register: CIRCLECICLI_INSTALLED
      changed_when: false

    - debug:
        var: CIRCLECICLI_INSTALLED
